### ISSUE TITLE
[ISSUE] Cum inside 15 times daily task

### ISSUE THREAD

**Issue by Keiki-FD** [itsamewayu/OLFallenDoll#379] opened 2021-12-11 23:28 UTC
**Describe the bug**
Simultaneous orgasm does not count in the "cum inside 15 times" daily task, even tho the male clearly cums inside.

**Expected behavior**
The daily task should progress when cumming inside with simultaneous orgasm. :)

**Comment by jinjin525** [comment] 2021-12-12 07:07
Duplicate of #164

**Closed by jinjin525** 2021-12-12 07:07 UTC
