### ISSUE TITLE
[Harem] Currency lost after reconnecting

### ISSUE THREAD

**Issue by Tuzo9** [itsamewayu/OLFallenDoll#124] opened 2021-11-30 07:34 UTC
**Describe the bug**
When I started the game. Probably 30 mins after the update, before server crash I got a fatal error and lost all my currency including the booster pack thing. Obviously I can’t reproduce it or anything.

**Comment by jinjin525** [comment] 2021-12-06 07:25
Duplicate of #102

**Closed by jinjin525** 2021-12-06 07:25 UTC
