### ISSUE TITLE
[Issue] Scene causes camera to move out of zone

### ISSUE THREAD

**Issue by fduser2** [itsamewayu/OLFallenDoll#229] opened 2021-12-02 12:17 UTC
![image](https://user-images.githubusercontent.com/95328775/144420241-0a18573c-2f5f-4e39-aee1-6654d2cbc725.png)

Scene cunnilingus piledriver Alet x Dr Anya causes camera to move out of zone

**Comment by jinjin525** [comment] 2021-12-06 11:00
Duplicate of #168

**Closed by jinjin525** 2021-12-06 11:00 UTC
