### ISSUE TITLE
Account problem

### ISSUE THREAD

**Issue by Charlotte-RE** [itsamewayu/OLFallenDoll#147] opened 2021-11-30 15:01 UTC
線上帳號被強制下線後再到線上只能重辦新ID
After the account is forcibly logged out, it can only be renewed

**Comment by GroverChouT** [comment] 2021-12-01 10:42
#154

**Comment by jinjin525** [comment] 2021-12-06 08:27
confirmed Duplicate of #154

**Closed by jinjin525** 2021-12-06 08:27 UTC
