### ISSUE TITLE
[animation] Spray water that is repeated all the time

### ISSUE THREAD

**Issue by DarkRaven2023** [itsamewayu/OLFallenDoll#618] opened 2023-03-05 16:41 UTC
**Describe the bug**
The fluids system has anomalies in gallery mode, such as Alet's water spray animation after orgasm after being inserted into the vagina, no matter which male animal will cause this result
**To Reproduce**

1. Go to 'gallery mode'
2. Click on 'Alet'
3. Scroll down to 'Press the button for body sperm or withdrawal'
4. See error   'Constantly squirting water or urine '

**Expected behavior**
Supposedly, It stands to reason that spraying urine or water is only for a while, and it will not continue without stopping

**Screenshots**
![20230306001514_1](https://user-images.githubusercontent.com/127008409/222973528-22270809-b49f-4929-a595-12c2ad7cb276.jpg) (As long as it happens once, the character will play the water spray animation non-stop)

OS: Win11
Game Version [e.g. 0.7.0]
Complete the following Computer Hardware Configurations if necessary:
Processor(CPU): [e.g. i5-12600K]
Graphics Card:[e.g. RTX 3050]
Memory:[e.g. 32GB]

**Comment by poykun** [comment] 2023-03-05 18:12
Duplicate of #612 
Very low on the priorities list as this and other gallery bugs are likely due to animations tweaks and features not being supported by the gallery. It'll require a new rebuild like harem.

**Closed** 2023-06-15 08:40 UTC
Labels: duplicate
