### ISSUE TITLE
[UI] Preview the costume before buying

### ISSUE THREAD

**Issue by bestpika** [itsamewayu/OLFallenDoll#111] opened 2021-11-30 06:30 UTC
**Is your feature request related to a problem? Please describe.**

Currently it is not possible to preview how the garment will look before you buy it, which is inconvenient.

**Describe the solution you'd like**

I wish I had a preview of how it would look before I bought it.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by jinjin525** [comment] 2021-12-06 06:36
Duplicate of #95 .

**Closed by jinjin525** 2021-12-06 06:36 UTC
Labels: duplicate
