### ISSUE TITLE
Blurred [Harem Mode]

### ISSUE THREAD

**Issue by DerLederlappen** [itsamewayu/OLFallenDoll#189] opened 2021-12-01 03:57 UTC
When I go into harem mode, the characters become blurry as you can see in the attached pictures. 
![20211201045307_1](https://user-images.githubusercontent.com/95330022/144169314-2dd2e615-581c-4b8c-a653-f5a72814738f.jpg)
![20211201045326_1](https://user-images.githubusercontent.com/95330022/144169330-820703dd-a9d5-4a79-bbc3-babccc062ec4.jpg)

**Comment by jinjin525** [comment] 2021-12-06 12:18
Duplicate of #183

**Closed by jinjin525** 2021-12-06 12:18 UTC
Labels: duplicate
