### ISSUE TITLE
[0.7.6b] belly bulge reset is not working in Erotes and with strange issue

### ISSUE THREAD

**Issue by kmoonwalker** [itsamewayu/OLFallenDoll#960] opened 2023-11-02 06:48 UTC
So when you enter any glory hole or sit on sofa and click to drain internal fluids you see the text but there is no sound of it (btw when you add sound back pls make it quieter + same to walking sounds)

When you do that on sofa and stand up you see effect that after few seconds belly grows back...

https://github.com/itsamewayu/OLFallenDoll/assets/71607540/dedcce05-a82f-4684-b024-fa2caaf096cc

Video by courtesy of SoulWizard due to camera limitations introduced one can't film this alone :/

**Comment by kmoonwalker** [comment] 2023-11-02 08:43
it seems that client is not synchronizing properly with server and after data sync following standing up  belly bulge is restored to state that it was 2,6 liter here

**Comment by TheSoulWizard** [comment] 2023-11-25 21:48
Seems like it works as intended now.

https://github.com/itsamewayu/OLFallenDoll/assets/40411642/8edfa91d-65cd-4a0a-97b5-a05f7a589dd8

Closing as resolved.

**Closed** 2023-11-28 07:48 UTC
Labels: bug, 0.7.6
