### ISSUE TITLE
After adjusting resolution, unable to make use of all of my screen

### ISSUE THREAD

**Issue by lastttoshred** [itsamewayu/OLFallenDoll#208] opened 2021-12-02 00:19 UTC
I made an adjustment to the resolution of the game, to 2560x1440 and now am unable to move my mouse past those "barriers" this unable to make full use of my screen, or even change the resolution to fix the issue

**Comment by Mark3456345** [comment] 2021-12-03 00:14
Same issue.

**Comment by jinjin525** [comment] 2021-12-06 13:45
Duplicate of #74

**Closed by jinjin525** 2021-12-06 13:45 UTC
