### ISSUE TITLE
[UI] 阿蕾特的猫猫内裤在穿上后，重新登陆就会消失

### ISSUE THREAD

**Issue by HESH7744** [itsamewayu/OLFallenDoll#1848] opened 2024-08-14 13:19 UTC
**Describe the bug**
给阿蕾特穿上猫猫内裤后，只要重新登陆，阿蕾特就会进入没穿内裤的状态

**Comment by Awfulwaffle1** [comment] 2024-09-13 06:02
Cannot reproduce as of 0.8.4c. Marking as Resolved and closing.

**Closed as completed by Awfulwaffle1** 2024-09-13 06:02 UTC
Labels: Resolved
