### ISSUE TITLE
[Resolution] Mouse Scaling with Ultra Widescreen Monitors

### ISSUE THREAD

**Issue by itsamewayu** [itsamewayu/OLFallenDoll#35] opened 2021-11-27 11:54 UTC
Maru — Yesterday at 10:32 PM
Mouse doesn't properly scale with Ultra Widescreen monitors at 32:9 5120x1440
Needs to be slightly above a button to be able to click it
![unknown](https://user-images.githubusercontent.com/11155504/143680222-e51cb7e2-2933-4442-8b59-613e1a340eab.png)
![unknown](https://user-images.githubusercontent.com/11155504/143680224-ff31be03-22d7-47e2-98dd-6405b8a517f7.png)

![unknown](https://user-images.githubusercontent.com/11155504/143680227-84e79059-fe2e-4d41-b96e-ea2927643e6c.png)

**Comment by clifftor** [comment] 2021-11-27 14:44
Possible dupe of https://github.com/itsamewayu/OLFallenDoll/issues/27

**Comment by itsamewayu** [comment] 2021-11-28 05:49
Perhaps, issue #27 did not state what the direct issue is though just that the mouse was off

**Comment by Cryshah** [comment] 2021-11-30 23:07
I have a samsung G9, and to have proper resolution, i have to put game to 1920x1200 windowed, then return to 5120x1440 full
at each launch

**Comment by jinjin525** [comment] 2021-12-07 06:28
Merge with #27

**Closed by jinjin525** 2021-12-07 06:28 UTC
