### ISSUE TITLE
Everytime You push Harem mode, it will force you to create a new user name and it resets everything.

### ISSUE THREAD

**Issue by DudeOfCulture** [itsamewayu/OLFallenDoll#638] opened 2023-03-06 12:37 UTC
After Being able to login to Harem mode you're suppose to enter a name and pick an option. Each time I enter Harem Mode, it will reset and ask me to enter the name again. However the name I previously used will no longer be available and it will reset everything from the previous login.

**Comment by pshnawnawman** [comment] 2023-03-06 17:33
I'm experiencing this same issue. My account from before the new update seems to be missing (and I'm afraid I've somehow overwritten it by using the same name for one of the "new accounts" that I've been prompted to create). I'm hoping to get that original account restored, since it had a lot of progress on it. I haven't done any patreon linking yet either, since the discord warns that it's currently a bit unstable.

**Comment by Awfulwaffle1** [comment] 2023-03-06 22:46
Duplicate of #635

**Comment by smkeye** [comment] 2023-03-07 00:08
I have had the same experiance.  Tried logging in this morning and made one account.  Tried to log in this evening and was asked to create an account again.

**Closed** 2023-07-27 10:47 UTC
Labels: duplicate
