### ISSUE TITLE
[Animation]安雅博士-挂腿骑乘位-内射-动画错误

### ISSUE THREAD

**Issue by makuro0086** [itsamewayu/OLFallenDoll#385] opened 2021-12-13 13:48 UTC
**Describe the bug**
 is.在挂腿骑乘位选内射后安雅博士会进入骑乘位的动画（如图）
**To Reproduce**
1. Go to '挂腿骑乘位'
2. Click on '内射'
3. See error

**Expected behavior**
正常显示动画

**Screenshots**
![Inked20211213203029_1_LI](https://user-images.githubusercontent.com/96062890/145823924-5db6362e-465d-4f65-a54a-4fe7d1591dd6.jpg)

**Desktop (please complete the following information):**
 - OS: [e.g. Win10]
 - Game Version [ 0.42]
 Complete the following Computer Hardware Configurations if necessary:
 - Processor(CPU): [i7-11800H]
 - Graphics Card:[RTX 3060]
 - Memory:[16GB]

**Comment by jinjin525** [comment] 2021-12-19 07:14
Confirmed duplicate of #347

**Closed by jinjin525** 2021-12-19 07:14 UTC
