### ISSUE TITLE
[Controls] exit button after a scene

### ISSUE THREAD

**Issue by fduser2** [itsamewayu/OLFallenDoll#185] opened 2021-12-01 03:17 UTC
Button sometimes causes UI to be unresponsive. Can still move the camera and mouse around but game does not respond to other input (buttons on screen unresponsive, esc button does not pull up menu)

**Comment by fduser2** [comment] 2021-12-01 03:18
*exit button after a scene (after orgasm)

**Comment by jinjin525** [comment] 2021-12-06 12:00
Duplicate of #100

**Closed** 2021-12-06 14:39 UTC
