### ISSUE TITLE
[Model][Scene]Model shifts in certain pose

### ISSUE THREAD

**Issue by 47AqUa** [itsamewayu/OLFallenDoll#392] opened 2021-12-15 07:18 UTC
**Describe the bug**
[Alet Missionary Massage]
In this pose, model will shift if player uses special position or cum again. When the animation is over, then model will teleport back to the original location.

**To Reproduce**
1. Choose [Alet Missionary Massage]
2. Trigger Special 1 or Cum again

**Expected behavior**
Animation would be done without shifting

**Screenshots**
https://drive.google.com/file/d/1IezbMCFJ4l5x4Vyq-SpHuyxykfXIWv10/view?usp=sharing
https://drive.google.com/file/d/1qS47LnmtIgzOmHRTy1eXL5m7CGf7nFwf/view?usp=sharing

**Desktop (please complete the following information):**
 - OS: Win10
 - Game Version 0,42
 Complete the following Computer Hardware Configurations if necessary:
 - Processor(CPU): i7-8750H
 - Graphics Card: GTX 1070
 - Memory: 16GB

**Comment by jinjin525** [comment] 2021-12-19 07:27
Duplicate of #246

**Closed by jinjin525** 2021-12-19 07:27 UTC
