### ISSUE TITLE
Closing Player List UI prevents the camera from being panned.

### ISSUE THREAD

**Issue by redwash** [itsamewayu/OLFallenDoll#871] opened 2023-08-02 17:25 UTC
If the "Player List" UI element (Top left of screen) is minimised then after a couple of seconds the camera can no longer be panned.

**To Reproduce**
Click on the Player List tab to minimnise it and then right click to pan the camera. For the first few seconds the right click enables camera movement (Can be moved as long as RMB is held) but after a few seconds, or if the right click is released and then re-clicked, the camera will no longer pan.

**Expected behavior**
Right click should pan the camera at any time.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Game Version 0.7.41
 Complete the following Computer Hardware Configurations if necessary:
 - Processor(CPU): 13900k
 - Graphics Card: 4090
 - Memory: 32GB

**Comment by johnathandarkly** [comment] 2023-08-08 06:19
seems like duplicate of #811

**Comment by Awfulwaffle1** [comment] 2023-09-05 01:23
Duplicate issue. Closing.

**Closed by Awfulwaffle1** 2023-09-05 01:23 UTC
Labels: duplicate, System, 0.7.41
