### ISSUE TITLE
[System]when press the bottom hide (a player) in game ,then will back to menu

### ISSUE THREAD

**Issue by jrf01** [itsamewayu/OLFallenDoll#271] opened 2021-12-03 05:16 UTC
**Describe the bug**
When press the buttom hide (a player) in game ,then will back to menu
I pressed hide tag from the bottom of the player list to hide a player in order to increase my FPS ,then bug appear(It appears when I hided two players).
我在玩家列表里面点击隐藏玩家的按钮后，游戏会自动返回主菜单。
**To Reproduce**
1.Open the player list
2.press the buttom "HIDE" from the bottom of the player list
3.When you hide two of them , the bug appears.
1.打开玩家列表
2.从底部的玩家开始点击隐藏
3.点击两个后会自动返回主菜单
**Expected behavior**
Hide the player to increase my FPS
隐藏玩家以提升我的帧数
**Desktop**
 - OS: Windows11
 - Hardware:CPU: Intel i7 10700k  Graphic Card: RTX 3070 RAM: 16G DDR4
 - Version 0.4.1

**Comment by johnathandarkly** [comment] 2021-12-03 18:18
this bug also triggers when you press the same hide icon twice. 

ps: please don't fix this until the inescapable experiment bug is fixed... the double hide bug is the only way i can escape to the main menu without killing the game. :)

**Comment by jinjin525** [comment] 2021-12-07 04:20
Duplicate of #217

**Closed by jinjin525** 2021-12-07 04:20 UTC
