### ISSUE TITLE
[Model]Mesh Clipping Ayana standard outfit

### ISSUE THREAD

**Issue by alfi301** [itsamewayu/OLFallenDoll#134] opened 2021-11-30 08:44 UTC
I was performing an animation with Dr.Ayanas standard outfit. It was the handjob with the blue guy. In the animation itself the outfit was fine but after the animation finished, the part of Ayana that should be naked was not present (invisable). The parts of the outfit were there and the face was visable too.
Sadly I was not able to make a screenshot because game crashed slightly after

**Comment by alfi301** [comment] 2021-11-30 15:54
I managed to reproduce and get a screenshot
![Screenshot (155)](https://user-images.githubusercontent.com/95278116/144080949-b0525243-5e28-4a73-8c3a-9bc78778ca19.png)
also in some animations the neck seems to be missing. See here: 
![Screenshot (156)_LI](https://user-images.githubusercontent.com/95278116/144081186-166e98b3-7aa9-46de-b990-5a6766fcc192.jpg)

**Comment by jinjin525** [comment] 2021-12-06 07:58
duplicate of #70

**Closed by jinjin525** 2021-12-06 07:58 UTC
Labels: duplicate
