### ISSUE TITLE
Expermient Filer (Cards sorting) not working. Anya Cards in Alet set, Alet cards in Erika set etc.

### ISSUE THREAD

**Issue by Panthear** [itsamewayu/OLFallenDoll#368] opened 2021-12-09 12:34 UTC
Minor issue: The filtering of the experiment by person does have some errors. Some cards are listed under Alet, though they clearly belong to other set. Following cards were seen not placed correctly:

Alet Set, but Dr Anya or Erika:
=> Anal Missionary
=> Threesome Reverse Cowgirl Double Penetration
=> Prone Bone
=> Hands Bound Missionary
=> Threesome kneeling Splitraost with Standing Blowjob
=> Hugging Cowgirl
=> Thrust behind
=> Reverse Footjob
=> Squatting Cowgirl
=> Betty Rocker

Erika Set, but Alet or Anys:
=> Doggystly Massage
=> Leg-Raised Missionary
=> Reclined Entry
=> Leg-Up Kneeling Blowjob
=> Fondling Handjob
=> Handcuffed Crouch Anal
=> Bent over rear entry On ....

Anya's set, but Alet or Erika
=> Kneeling Missionary
=> Doggystyle on Crane
=> On Back Footjob

Attached Sample Screenshot (of the first issue)
![grafik](https://user-images.githubusercontent.com/95415732/145397221-99414d8c-52cc-4acf-9e59-c4a40687efc6.png)

Additional Enhancement Request: It would be nice if you could filter by Male and Type (as some dailies request for Type...)

**Comment by jinjin525** [comment] 2021-12-10 07:32
Duplicate of #113

**Closed by jinjin525** 2021-12-10 07:32 UTC
Labels: duplicate
