### ISSUE TITLE
[system,connection]I have to regist ID again each time after entering game每次进入游戏都要重新注册一次ID

### ISSUE THREAD

**Issue by z79291638** [itsamewayu/OLFallenDoll#130] opened 2021-11-30 08:01 UTC
**Describe the bug**
在退出游戏以后再进入游戏点击后宫模式第一次会连接不上（一直在loding），取消以后再次连接就会要求重新注册ID，之前的ID还会显示已被使用。

**Desktop (please complete the following information):**
 - OS: [windows 10]
 - Browser [chrome,]
 - Version [playtest]

**Comment by GroverChouT** [comment] 2021-12-01 10:42
#154

**Comment by jinjin525** [comment] 2021-12-06 07:39
Confirmed duplicate of #154 . More detailed in issue No.154

**Closed by jinjin525** 2021-12-06 07:39 UTC
