### ISSUE TITLE
[Harem] [UI]Even if a pair reaches the climax at the same time, it will not be counted as the climax of each individual character.

### ISSUE THREAD

**Issue by Kasaiji** [itsamewayu/OLFallenDoll#279] opened 2021-12-03 14:45 UTC
**Describe the bug**
Even if a pair reaches the climax at the same time, it will not be counted as the climax of each individual character.
Erica's daily task came out on December 3rd, but the pair's climax wasn't counted.
I later confirmed that the individual climaxes were counted without any problems.

**video**
https://drive.google.com/file/d/1Ph_8avFwnBtdp21CGP8x5kKgpi6vUCo3/view?usp=sharing

**Desktop (please complete the following information):**
- OS: [windows 10 home]
- RAM: [32GB]
- video card: [Geforce RTX 2060 Super]
- CPU: [Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz 4.00 GHz]

**Comment by johnathandarkly** [comment] 2021-12-03 18:14
i couldn't figure out why i was an orgasm short today, but one of Erica's was simultaneous, so this checks out for me.

**Comment by jinjin525** [comment] 2021-12-07 04:39
Duplicate of #164

**Closed by jinjin525** 2021-12-07 04:39 UTC
