### ISSUE TITLE
[UI] Delete key removes UI

### ISSUE THREAD

**Issue by jstibbsy** [itsamewayu/OLFallenDoll#104] opened 2021-11-30 06:03 UTC
**Describe the bug**
Pressing the Delete key (del) removes UI permanently

**To Reproduce**
1. Go into Harem mode
2. Click start
3. Load in and press delete

**Expected behavior**
Nothing to happen.

**Desktop (please complete the following information):**
 - OS: Windows 11

**Comment by TheSoulWizard** [comment] 2022-01-02 02:49
Could you try this and tell if it's still present or not? On my end, pressing delete does nothing.

**Comment by Awfulwaffle1** [comment] 2023-08-19 23:46
Could not reproduce as of 0.7.41. Closing.

**Closed by Awfulwaffle1** 2023-08-19 23:46 UTC
Labels: Cannot Reproduce
