### ISSUE TITLE
Blurr costume in Harem mode

### ISSUE THREAD

**Issue by brandonbongbong** [itsamewayu/OLFallenDoll#417] opened 2021-12-27 05:33 UTC
**Describe the bug**
Blurry costume is shown in Harem mode but works fine in Gallery mode. Settings all set to high.

**To Reproduce**
1. Go to 'Harem mode'

**Expected behavior**
Costume should be displayed no blurry 

**Desktop (please complete the following information):**
 - OS: [e.g. Win10]
 - Game Version [0.42]

**Comment by jinjin525** [comment] 2021-12-29 05:50
Duplicate of #183

**Closed by jinjin525** 2021-12-29 05:50 UTC
