### ISSUE TITLE
[Model] Character not loading and stuck in spawn room

### ISSUE THREAD

**Issue by Exarch23** [itsamewayu/OLFallenDoll#101] opened 2021-11-30 05:54 UTC
**Describe the bug**
When I start harem mode after selecting a character it spawns me in the chamber in between the rooms.  There is no character visible
and I cant move around, the only thing I can do is move my camera and navigate around the HUD elements that are tied to keys.

**To Reproduce**
1. Go to 'Harem Mode'
2. Click on 'Character of choice'
3. Click on 'Start'

**Screenshots**
![Screenshot](https://i.gyazo.com/3cc806b8eea901f06951d758a05a1ffe.jpg)

**Comment by 1843890303** [comment] 2021-11-30 06:02
Can reproduce, game is still unplayable even after a fresh install, any workaround?

**Comment by hlfblkcafe** [comment] 2021-11-30 06:03
Can reproduce has been reproducing

**Comment by hlfblkcafe** [comment] 2021-11-30 06:04
https://gyazo.com/3cc806b8eea901f06951d758a05a1ffe

**Comment by Exarch23** [comment] 2021-11-30 06:59
Update: I was able to play and move around and spawn my character, it seems that this is matchmaking/server based , I needed to keep going back and forth to main menu and booting harem mode to match make to a room with players inside, I have reproduced this twice now, after that got stuck in a pose and I'm currently trying to find a good lobby again.

**Comment by Fank** [comment] 2021-11-30 12:31
I tried it multiple times (menu <-> harem), never manage to get a character to spawn, my camera where only onto of the pillar in the center while unable to move.

**Comment by jinjin525** [comment] 2021-12-06 14:03
From ItalianMeatball in issue #216 
After patch 0.4.2 instead of infinite loading the game kicks you back to main menu after trying to connect, it boils down to the same problem, the issue is not fixed.

**Comment by poykun** [comment] 2022-02-06 03:58
Another endless loading screen reported by Postal Penguin in discord. 
Endless loading screen with no kickback to the main menu.
Was able to play initially, but could not the next day.

Tried reinstalling, verifying file integrity and restarting router.

**Comment by Awfulwaffle1** [comment] 2023-08-20 04:26
We've got a few issues open and resolved through different methods. Kick back to Main Menu is currently due to networking issues either clientside or server side. A new update for server networking is pending. Closing this one, but will create another if the problem persists.

**Closed by Awfulwaffle1** 2023-08-20 04:26 UTC
Labels: Centralized discussion
