### ISSUE TITLE
[UI] [ALET] NYAN BOTTOM always automatically unequipped after re login 

### ISSUE THREAD

**Issue by HESH7744** [itsamewayu/OLFallenDoll#1840] opened 2024-08-10 16:26 UTC
**Describe the bug**
The Alet's NYAN BOTTOM always unequipped after re login

**To Reproduce**
1. Equip the NYAN BOTTOM
2. Log out and log in again
3. The "equipped" status of NYAN BOTTOM disappeared. (Nothing on the lower)

**Comment by Awfulwaffle1** [comment] 2024-09-13 06:03
Cannot reproduce as of 0.8.4c. Marking as Resolved and closing.

**Closed as completed by Awfulwaffle1** 2024-09-13 06:03 UTC
Labels: Resolved
