### ISSUE TITLE
Daily Task incompletable and unreadable

### ISSUE THREAD

**Issue by User7276** [itsamewayu/OLFallenDoll#472] opened 2022-01-05 17:31 UTC
3rd daily task incompletable and unreadable.
![20220105092927_1](https://user-images.githubusercontent.com/95495776/148262505-04c6ad8a-7a7a-4259-992b-8172ca11374b.jpg)

**Comment by poykun** [comment] 2022-01-05 18:15
Dupe of #446

**Closed** 2022-01-06 20:33 UTC
