### ISSUE TITLE
[Model] Clothing Changes Not Persistent

### ISSUE THREAD

**Issue by Jinklez** [itsamewayu/OLFallenDoll#807] opened 2023-06-27 02:44 UTC
**Describe the bug**
Changing costumes on characters, inside harem or in costume select screen is not properly saved.  Sometimes it updates correctly, mostly it does not. Neither is updating characteristics such as hair colour.

**To Reproduce**
Change costume.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win10
 - Game Version: Latest (0.73?)

**Comment by Awfulwaffle1** [comment] 2023-07-20 22:02
possible duplicate of #768

**Comment by Awfulwaffle1** [comment] 2023-07-27 09:53
Closing due to duplicate issue

**Closed by Awfulwaffle1** 2023-07-27 09:53 UTC
Labels: duplicate, Costume, 0.7.3
