### ISSUE TITLE
Experiment Juzi Revenant  incorrect intercourse

### ISSUE THREAD

**Issue by jmalkovich18** [itsamewayu/OLFallenDoll#1396] opened 2024-03-24 07:15 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Win10/Ubuntu 20.04]
 - Game Version [e.g. 0.42]
 Complete the following Computer Hardware Configurations if necessary:
 - Processor(CPU): [e.g. i7-9700K]
 - Graphics Card:[e.g. RTX 2070s]
 - Memory:[e.g. 16GB]

*If your game crashed, remember to upload the dmp file with your issue.

It's located in C:\Users\ (USER ID) \AppData\Local\Paralogue

OS: Win10
Game Version 0.8.0
Complete the following Computer Hardware Configurations if necessary:
Processor(CPU): i5-9400F
Graphics Card: GeForce GTX 3060
Memory: 16GB

On card symbol said vaginal but in game its anal. Is it POSSIBLE to fix this to VAGINAL???

![FallenDoll   3_22_2024 7_54_41 PM](https://github.com/itsamewayu/OLFallenDoll/assets/163656510/05c3d86a-88fd-4ee2-87ec-de5c270ef910)

**Comment by Awfulwaffle1** [comment] 2024-03-27 16:16
dupe of #1361 closing.

**Closed as completed by Awfulwaffle1** 2024-03-27 16:16 UTC
Labels: duplicate
