### ISSUE TITLE
Infinite Loading

### ISSUE THREAD

**Issue by Corf485** [itsamewayu/OLFallenDoll#224] opened 2021-12-02 11:07 UTC
**Describe the bug**
Click Harem mode, get Loading please wait forever, Been like this since hour 4 of beta release

**To Reproduce**
1. Go to 'Main Menu'
2. Click on 'Harem'
3. See error

**Expected behavior**
I should be able to access the Harem menu with characters/poses/play

**Screenshots**
![image](https://user-images.githubusercontent.com/95322437/144400811-6b9f9418-bc89-453e-b9b3-0a4eed254511.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10 Pro]
 - Version: [19043.1348???]
**Additional context**
Happened about 4 hours after release of beta, I waited for patch to release this bug report, patch came, nothing changed.

I've done about everything I can think of including:

Verifying Files multiple times
Uninstalling/Reinstalling 10+ times
Restarting Steam multiple times
Restarting PC, I completely shut it down for the night
Restarting Modem
Launching Only FDOL

**Comment by ItalianMeatball** [comment] 2021-12-02 13:27
Same issue as mine

**Comment by anonymouskommando** [comment] 2021-12-03 01:33
Same issue for me, refer to "unable to enter harem mode" ticket for my system specs. Issue not resolved by 4.1 patch.

**Comment by ItalianMeatball** [comment] 2021-12-04 21:55
After patch 0.4.2 instead of infinite loading the game kicks you back to main menu after trying to connect, it boils down to the same problem, the issue is not fixed.

**Closed** 2021-12-06 08:30 UTC
