### ISSUE TITLE
[Harem] [UI] Daily tasks that specify tags are not counted

### ISSUE THREAD

**Issue by Kasaiji** [itsamewayu/OLFallenDoll#278] opened 2021-12-03 14:42 UTC
**Describe the bug**
Femdom tag daily task counts are not accumulated.
Similarly, the December 2nd Interspecies tag was not counted either.

**video**
https://drive.google.com/file/d/1Ph_8avFwnBtdp21CGP8x5kKgpi6vUCo3/view?usp=sharing

**Desktop (please complete the following information):**
- OS: [windows 10 home]
- RAM: [32GB]
- video card: [Geforce RTX 2060 Super]
- CPU: [Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz 4.00 GHz]

**Comment by jinjin525** [comment] 2021-12-07 04:38
Duplicate of #164

**Closed by jinjin525** 2021-12-07 04:38 UTC
