### ISSUE TITLE
Harem Mode Stealing Data Fragments

### ISSUE THREAD

**Issue by thorping** [itsamewayu/OLFallenDoll#741] opened 2023-04-18 04:16 UTC
A few times when I have cashed in Data Fragmebts after witnessing experiments, it is overcharging me for the given blueprint. For instance, charging 10 DF instead of 5 for a Green blueprint. 

Not sure how to reproduce since it happens sporadically. This time it happened when purchasing Item No. 340. 

**Expected behavior**
Expected to be charged 5 Data Fragments instead of 10. This has happened a couple of times before when purchasing other items. 

**Screenshots**
Sorry, do not have a screenshot that represents this. 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Game Version 0.7.1b
 Complete the following Computer Hardware Configurations if necessary:
 - Processor(CPU): 12th Gen Intel Core i7-127-00T 
 - Graphics Card: UHD Graphics 770 / RTX 3050
 - Memory: 32 GB 

*If your game crashed, remember to upload the dmp file with your issue.

Game did not crash. 

**Additional context**

**Comment by thorping** [comment] 2023-04-21 07:00
Happened again… video posted.

**Comment by thorping** [comment] 2023-04-21 07:06
Happened again. Before and after photos attached. 
![D18D8251-5A72-408D-9E9B-3269EBC929D5](https://user-images.githubusercontent.com/130284348/233565577-a4cc1ab2-692c-45ed-8ded-d391d269256f.png)
![22E722C7-CE51-4595-8479-5181B9829D83](https://user-images.githubusercontent.com/130284348/233565587-f96ed0ec-3dc6-44ba-9536-f83649cbe994.png)

**Comment by Awfulwaffle1** [comment] 2023-05-31 02:16
Dupe of #465. Closing.

**Closed by Awfulwaffle1** 2023-05-31 02:16 UTC
Labels: ADDRESSED
