### ISSUE TITLE
Account is lost after linking to Patreon 

### ISSUE THREAD

**Issue by Reiculu** [itsamewayu/OLFallenDoll#639] opened 2023-03-06 13:32 UTC
(Account and Network issues)
Hi,
my account is  lost and I need to recreate a account after I linked my Patreon account.
Every time it is taking me back to the player id section again but wont proceed because my old username is used. My patreon costumes and other things are gone.
What should I do now. Recreate another Account or wait until my account is restored?

**Comment by Awfulwaffle1** [comment] 2023-03-06 22:47
Duplicate of  #635

**Closed** 2023-07-27 10:48 UTC
Labels: duplicate
