### ISSUE TITLE
[Model] Feet clipping through Erika's shoes in "hands bound missionary"

### ISSUE THREAD

**Issue by apugo** [itsamewayu/OLFallenDoll#291] opened 2021-12-03 18:37 UTC
With the Hound of Tindalos: 

https://i.imgur.com/yEVdLCO.png

**Comment by apugo** [comment] 2021-12-03 21:51
It appears this may trigger when you activate the special action.

**Comment by jinjin525** [comment] 2021-12-07 06:13
Duplicate of #58

**Closed by jinjin525** 2021-12-07 06:13 UTC
