### ISSUE TITLE
[Model] Alet Ded Moroz's Present Bug

### ISSUE THREAD

**Issue by Altair91** [itsamewayu/OLFallenDoll#80] opened 2021-11-29 12:14 UTC
As you can see there is a bodyproblem and also as i noticed a little clipping error on the right Breast
![20211129020416_1](https://user-images.githubusercontent.com/70227970/143866229-7ac20ddc-10bd-4e0a-96c0-aa04a114d844.jpg)

**Comment by jinjin525** [comment] 2021-12-05 15:12
It's Anya not Alet. If this is what game displayed after clicking Alet x Dreamer, please report another issue, thanks.
And about Anya bug, Duplicate of #8

**Closed by jinjin525** 2021-12-05 15:12 UTC
