### ISSUE TITLE
[game] unknown file version Paralogue-Win64-Shipping.exe

### ISSUE THREAD

**Issue by finitedark** [itsamewayu/OLFallenDoll#304] opened 2021-12-04 22:06 UTC
When loading the game I get this popup from easy anti cheat: unknown file version: ~/Steam/steamapps/common/Oper~/Paralogue/Binaries/Win64/Paralogue-Win64-Shipping.exe

 - OS: Windows 8.1
 - Game Version 0.4.2

**Comment by jinjin525** [comment] 2021-12-07 06:50
Duplicate of #303

**Closed by jinjin525** 2021-12-07 06:50 UTC
Labels: duplicate
