### ISSUE TITLE
patreon无法连接

### ISSUE THREAD

**Issue by 0b5erv3r** [itsamewayu/OLFallenDoll#611] opened 2023-03-05 12:19 UTC
**Screenshots**
![image](https://user-images.githubusercontent.com/95467385/222960075-90e81250-5149-42a1-b253-18f89db401c5.png)

**Comment by poykun** [comment] 2023-03-05 13:42
Duplicate of #596 
Dev team is aware of the issue and working on a fix.

**Closed** 2023-06-11 08:05 UTC
Labels: duplicate, Resolved
