### ISSUE TITLE
[Harem] Can't exit pose after finishing experiment

### ISSUE THREAD

**Issue by RueGorE** [itsamewayu/OLFallenDoll#100] opened 2021-11-30 05:51 UTC
As stated in the title. Once I completed an experiment and clicked the button next to Play, both buttons went grey. I can still free look around but pressing the ESC key to Exit Pose isn't responding, neither is the 1 key for SPECIAL 1.

I heard of at least one other person in the Discord experiencing the same issue.
![Capture](https://user-images.githubusercontent.com/68206765/143992905-8298c456-643e-4093-8b3a-e17d543d0c3c.PNG)

**Comment by salsabeard** [comment] 2021-11-30 16:50
I just ran into something similar.  I finished and experiment and tried to exit, but it locked out the game entirely.  It's completely frozen and not responding to any input, but music is still playing.  

Interesting. While typing this up, the game finally closed.  I suspect whatever was locked up finally finished processing and it then took the ALT+F4 that I had attempted about 10 minutes ago.

**Comment by scocansa** [comment] 2021-11-30 19:50
Similar problem here.
Although as my UI shown, it looks like I did semi-exit the experiment.
It shows the usual roaming UI below but I could still interact with 1 key and 2 key.
No response with ESC key as well but fortunately I can straight ALT+F4 to terminate the game.
![20211201074059_1](https://user-images.githubusercontent.com/13067946/144116579-f31cd398-5ea3-4569-905f-15ff66bf9ff7.jpg)

**Comment by jinjin525** [comment] 2021-12-06 06:06
From hark6113 in issue No.180:
To Reproduce:
1.Try an experiment
2.make one of the participant climax
3.Try to leave during the climax animation
4.See error
OS: Win10

**Comment by TheSoulWizard** [comment] 2022-01-02 02:36
I believe this has been fixed in 0.4.5

**Closed** 2023-08-19 23:42 UTC
Labels: Centralized discussion
