### ISSUE TITLE
Everytime when I enter the harem mode，it always wants me to Create a new researcher.

### ISSUE THREAD

**Issue by 362399154** [itsamewayu/OLFallenDoll#636] opened 2023-03-06 12:28 UTC
[Network and account issue]
I can not enter the harem mode everytime,when I try to enter the harem mode,it always shows me to create a new researcher and I can not enter the harem mode by using in-game researcher name which I just used before.
I have linked to my Patreon account successfully and already received pledges,but I can not use it again when I try to retry to enter the harem mode.
In-game researcher name"洋洋宝贝"should linked to my Patreon account,please help me to solve it,really thank you!!!

**Comment by Awfulwaffle1** [comment] 2023-03-06 22:45
Duplicate of #635

**Closed** 2023-07-27 10:47 UTC
Labels: Resolved
