### ISSUE TITLE
Infinite Loading "Harem"

### ISSUE THREAD

**Issue by Kovjanko1** [itsamewayu/OLFallenDoll#96] opened 2021-11-30 05:30 UTC
**Describe the bug**
I load Into game Classic works fine and loads in a few seconds but whenever I click on "Harem" It never loads, but it does say "Loading Please Wait" but I have let it load for like an hour with no luck.

**To Reproduce**
Well I dont think its a bug for everyone but maybe for more than just me.

**Expected behavior**
The game to load after a few minutes

**Screenshots**

**Desktop (please complete the following information):**
Windows 10 Pro
Chrome and Firefox

**Smartphone (please complete the following information):**
 Samsung Galaxy S9 +
 Andriod Version 10
 Google
 

**Additional context**

**Comment by TheSoulWizard** [comment] 2021-11-30 05:32
Not a bug, servers are currently down.

**Comment by Kovjanko1** [comment] 2021-11-30 05:34
The whole time I tried yestarday and today?

**Comment by itsamewayu** [comment] 2021-11-30 05:37
If you tried yesterday it wasn't up yesterday whatsoever.

Today they've been up and down sporadically as Amazon Web Services think the players are DDoSing.

Closed as it's server issues.

**Closed by itsamewayu** 2021-11-30 05:37 UTC

**Comment by Kovjanko1** [comment] 2021-11-30 05:41
Thank you for the Info.
