### ISSUE TITLE
[model][animation] kneeling double dildo

### ISSUE THREAD

**Issue by DenkiKitsune** [itsamewayu/OLFallenDoll#437] opened 2021-12-28 23:32 UTC
**Describe the bug**
There are at least two issues I noted during this animation.  The first being that I was able to select multiple outfits that I do not yet own for both Anya and Erika.  The second is when Anya was wearing the Ded Moroz's Present.  Her upper torso and lower torso become disconnected.  Causing her to appear like a muppet.  If you remove the stockings her body re-attaches. You can also see some clipping of the outfit in the poses.
To note -  I am not always able to select different outfits that I do not own during all experiments.  It is possible that when I  studied an unknown experiment from another researcher this allowed me to access clothing that I currently do not have. 

**To Reproduce**
Place experiment.
Go to custom settings for clothing
Click on Ded Moroz's present for Anya
Enjoy the show

if this doesn't work with owed Experiment.
First attempt to study one then go to step 1

**Expected behavior**
Only change between outfits owned by player. Character model doesn't split in half.

**Desktop (please complete the following information):**
 - Win 11
 - ver 4.5
 - Processor(CPU): I7-10750H
 - Graphics Card: RTX 2070
 - Memory: 16gb

.
![20211228150511_1](https://user-images.githubusercontent.com/95551471/147614638-98559b1e-a448-4b6e-aea5-5a3f0143b2ca.jpg)
![20211228150357_1](https://user-images.githubusercontent.com/95551471/147614640-494b0ec6-ad94-4142-b559-9dfb92a26b83.jpg)
![20211228150407_1](https://user-images.githubusercontent.com/95551471/147614641-10c52568-6413-42ac-a11c-ba2b131ec0d9.jpg)
![20211228150412_1](https://user-images.githubusercontent.com/95551471/147614642-334a272f-c75d-4375-b4b2-ff5f31fc469e.jpg)
![20211228150426_1](https://user-images.githubusercontent.com/95551471/147614643-155504f7-5fe9-4bec-b530-32b65445c1bf.jpg)
![20211228150430_1](https://user-images.githubusercontent.com/95551471/147614644-a6441da2-3aa3-41fe-826d-b7f449cdd4c4.jpg)

It's located in C:\Users\ (USER ID) \AppData\Local\Paralogue

**Comment by jinjin525** [comment] 2021-12-29 07:07
I've been reported that the first issue is not limited to this scene only. Can you check if it's related to character or just the kneeling double dildo scene?
Second issue is a duplicate of #8

**Comment by DenkiKitsune** [comment] 2021-12-29 16:18
I apologize for reporting a know issue.  Thought I had done my due diligence and searched.  As for the first issue of being able to select different outfits in scenes that are not owned.  I did a quick check this morning and was able to select outfits with Erika in the foot licking scissoring scene (owned scene, which leads me to believe its an issue related to the scenes allowing access).  I'm going to have have to go through each scenes and make note of which ones allow me to switch.  Unfortunately I have purchased a couple outfits and don't owe all the scenes to fully compile which scenes allow access and which don't.

**Comment by DenkiKitsune** [comment] 2021-12-31 19:44
I've check a lot of these scene that I have access to.  It appears that lesbian scenes between two girls allow for access to various different clothing options that have not been purchased.  I have a spreadsheet that I'm working on as I gain access to scenes.  If anyone would like more details I'm happy to share.  I know that I'm not the only one reporting this issue.

**Closed** 2023-11-23 02:16 UTC
Labels: question, 0.4.5, Costume, Character
