### ISSUE TITLE
Player ID reset when using VPN and now cannot relogin

### ISSUE THREAD

**Issue by drmilkdecow** [itsamewayu/OLFallenDoll#186] opened 2021-12-01 03:19 UTC
**Describe the bug**
Hi, I created a player ID in the harem mode yesterday and managed to make some progress. However today when I changed my region using VPN to try to play the game, the game now asked me to create a new player ID.

Even after I stopped my VPN and is using my original IP, the game does not revert me back to my original player ID.

**To Reproduce**
1. Go to 'Harem Mode'
2. See error

**Expected behavior**
Expected behaviour is to see the logged in screen with Alet (or one of the girls) in the navigation menu waiting to start or customize.

**Screenshots**
See attached

**Desktop (please complete the following information):**
 - Browser [chrome]

**Comment by zyx27363** [comment] 2021-12-01 05:27
Same issue.
I created a player with VPN and when I restart the game it stucked in loading screen. So I changed a VPN IP to start the game then it asked me to input a new ID. Tried to login with the first VPN IP but it still asked me to create a new ID.

**Comment by GroverChouT** [comment] 2021-12-01 10:46
#154

**Comment by jinjin525** [comment] 2021-12-06 08:31
Confirmed duplicate of #154

**Closed by jinjin525** 2021-12-06 08:31 UTC
