### ISSUE TITLE
Main Menu Distortion and Loop

### ISSUE THREAD

**Issue by Eddy5646** [itsamewayu/OLFallenDoll#262] opened 2021-12-03 01:43 UTC
**Describe the bug**
When attempting to join the free roam area in Harem mode, the game fails to join in. 

Initially after failing, the game return to the Harem mode main menu screen - if an attempt to start the free roam again, you will be sent back to the game's main menu screen with it appearing somewhat distorted from normal (see image). 

When attempting to rejoin Harem mode from here, it will load into the Harem Mode Main Menu, however the text for the 'Start' button will be replaced with 'Resume.'

Clicking on the newly renamed 'Resume' button I believe just sends you back to the game's main menu, with the distortion as seen in the image (my memory is a bit foggy on this, it may send you to the free roam setup screen, and form there it sends you back to the game's main menu). This process can be continued as an infinite loop.

![Screenshot (55)](https://user-images.githubusercontent.com/95317506/144529461-39d7c306-b774-4e46-ab5f-3267873cc499.png)

**Comment by jinjin525** [comment] 2021-12-07 03:01
Duplicate of #176

**Closed by jinjin525** 2021-12-07 03:01 UTC
