### ISSUE TITLE
taskId:0 on reroll

### ISSUE THREAD

**Issue by fduser2** [itsamewayu/OLFallenDoll#452] opened 2022-01-01 16:23 UTC
on 0.4.6, rerolled one of the daily tasks and ended up with this. Persistent even after logging out/in harem

![image](https://user-images.githubusercontent.com/95328775/147855046-3bc5a188-a40e-4c5d-871e-472bc47128d2.png)

**Comment by poykun** [comment] 2022-01-01 17:14
Dupe of 446

**Closed** 2022-01-02 01:13 UTC
Labels: duplicate
