### ISSUE TITLE
Advanced Research Pass won't level up with Likes, only daily tasks

### ISSUE THREAD

**Issue by toxsickcity** [itsamewayu/OLFallenDoll#950] opened 2023-10-22 21:52 UTC
**Describe the bug**
Bug where as try to level up the advanced research Pass won't level up at all doing things like sex scenes and giving or receiving likes.
The only way I am seeing points increase is when daily challenges are done (I get 20 points per daily)

**To Reproduce**
Select any character as research Pass.
Perform sex scenes and then give likes. Received likes are also suppose to give points for research Pass but do not.

**Expected behavior**
As per the info hover icon it does say giving and receiving likes should increase points.

**Screenshots**
N/a

**Desktop (please complete the following information):**
 - OS: windows 10 pro
 - Game Version .. latest steam
 Complete the following Computer Hardware Configurations if necessary:
 - Processor(CPU): ryzen 5900x
 - Graphics Card: 3060
 - Memory: 64gb ddr4 3600

*If your game crashed, remember to upload the dmp file with your issue
N/a

It's located in C:\Users\ (USER ID) \AppData\Local\Paralogue

**Additional context**

**Comment by toxsickcity** [comment] 2023-10-23 08:32
It appears after the weekly reset. The likes are converting into advanced research Pass points.

Maybe Bux fixed after the weekly reset.
Or there is a limit per week of how many likes can be converted.

An answer would be welcomed at this point as this game is such a mixed bag of what's going on.

**Comment by Fiwzie** [comment] 2023-10-25 11:27
There's a limit of 1000 progress point gained by means other than daily missions and login, per week.

**Comment by Awfulwaffle1** [comment] 2023-11-23 05:52
Not a bug. Closing.

**Closed by Awfulwaffle1** 2023-11-23 05:52 UTC
Labels: Not A Bug, ADDRESSED
