### ISSUE TITLE
[Performance] Unable to Turn Off Motion Blur And V-Sync

### ISSUE THREAD

**Issue by ysy95109** [itsamewayu/OLFallenDoll#42] opened 2021-11-27 12:06 UTC
Motion blur and v-sync are still active despite appearing as turned off in the options menu.

**Comment by TheSoulWizard** [comment] 2021-11-28 00:38
Same with the v-sync. Im unable to get over 60 FPS. They won't unlock. (its not my GPU)

**Comment by jinjin525** [comment] 2021-12-05 09:45
Duplicate of #17 about motion blur.
Discussion moves to Issue No.17.

**Closed by jinjin525** 2021-12-05 09:45 UTC
Labels: duplicate
