### ISSUE TITLE
[UI] [Harem Mode] Daily Task -  [Foot] tag task does not tally

### ISSUE THREAD

**Issue by Exarch23** [itsamewayu/OLFallenDoll#273] opened 2021-12-03 10:28 UTC
The "Make male ejaculate to [Foot] tag pose" does not update the tally when I've done at least 4 times , ate up my sanity.

**Comment by jinjin525** [comment] 2021-12-07 04:24
Duplicate of #164

**Closed by jinjin525** 2021-12-07 04:24 UTC
