### ISSUE TITLE
[crash] fatal error giving likes

### ISSUE THREAD

**Issue by johnathandarkly** [itsamewayu/OLFallenDoll#416] opened 2021-12-26 09:26 UTC
**Describe the bug**
after an experiment, i was walking around giving likes. the second one resulted in a hard crash with the unreal engine "fatal error!" error.

**To Reproduce**
give one like too many.

**Expected behavior**
stay in the game, give more likes. :)

**Desktop**
 - OS: Win 10 Home
 - Game Version: 0.4.2
 - Processor: i7-4790k
 - Graphics Card: RTX 2060 Super
 - Memory: [16GB]
 
**Dump**
[UE4Minidump.zip](https://github.com/itsamewayu/OLFallenDoll/files/7776786/UE4Minidump.zip)

**Comment by Panthear** [comment] 2021-12-27 16:46
Sounds like a dupe of https://github.com/itsamewayu/OLFallenDoll/issues/400 ...

**Closed** 2021-12-28 07:25 UTC
