### ISSUE TITLE
Experiments/Animations wont play after selecting compatible location.

### ISSUE THREAD

**Issue by SpikyTheAnky** [itsamewayu/OLFallenDoll#371] opened 2021-12-09 17:00 UTC
**Describe the bug**
There seem to be some experiments that are not able to be played.

**To Reproduce**
1. Go to 'experiments menu while in a public harem mode lobby'
2. Click on '"Double Dildo Bulldog" for Erika and Anya'
3. Find a green compatible spot to play the animation. 
4. Nothing will happen after selection.

**Expected behavior**
I thought I was supposed to see the animation/experiment. It didn't play at all.

**Screenshots**

![20211209113400_1](https://user-images.githubusercontent.com/95874852/145440812-26ba1000-4bb7-4bc7-8c8d-9970e5e62c8b.jpg)

**Desktop (please complete the following information):**
 - OS: [e.g. Win10/Ubuntu 20.04]Windows 10
 - Game Version [e.g. 0.42] 0.4.2
 Complete the following Computer Hardware Configurations if necessary:
 - Processor(CPU): [e.g. i7-9700K] i7-8700k
 - Graphics Card:[e.g. RTX 2070s] RTK 2080
 - Memory:[e.g. 16GB] 32GB

**Additional context**

**Comment by jinjin525** [comment] 2021-12-10 07:37
Duplicate of #116

**Closed by jinjin525** 2021-12-10 07:37 UTC
