### ISSUE TITLE
[model][animation]Penis reveals missing neck in Anya "Threesome Kneeling Spitroast"

### ISSUE THREAD

**Issue by rroy6401** [itsamewayu/OLFallenDoll#351] opened 2021-12-07 03:20 UTC
**Describe the bug**
From a side view, Anya wearing just shoulder pads seems to be missing her neck, which is made clear by the Dreamer penis in teh animation

**To Reproduce**
1. Go to Harem Mode
2. Place "Threesome Kneeling Spitroast"
3. View from side

**Expected behavior**
Her to have neck that obscured the penis

**Screenshots**
![20211206195922_1](https://user-images.githubusercontent.com/4632606/144960132-3b22cace-39af-4ce5-acb4-04f7cf60e5ff.jpg)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10

**Additional context**

**Comment by johnathandarkly** [comment] 2021-12-07 03:25
covered by #70 i think

**Comment by jinjin525** [comment] 2021-12-07 08:55
Confirmed Duplicate of #70

**Closed by jinjin525** 2021-12-07 08:55 UTC
