### ISSUE TITLE
Account missing after linking Patreon

### ISSUE THREAD

**Issue by ThunderKatt** [itsamewayu/OLFallenDoll#640] opened 2023-03-06 14:34 UTC
Last night I was finally able to link my account to Patreon once the feature was working.  I was able to claim my rewards, battlepass items, and go into harem mode for awhile.  I logged out eventually since staying connected is still an issue, but when I woke up this morning and tried to log in to play I was met with the screen prompt asking to create my player ID again.  I didn't bother to make a new one and just exited the game and logged in again to see if it would load my normal account.  Instead I got the same screen again asking to make a new player ID.  Any help would be appreciated. Thanks.

**Desktop**
 - Windows 10 (64 bit)
 Complete the following Computer Hardware Configurations if necessary:
 - Intel(R) Core(TM) i7-5960X CPU
 - (2) Titan X 
 -32 GB RAM

**Comment by Awfulwaffle1** [comment] 2023-03-06 22:47
Duplicate of #635

**Closed** 2023-07-27 10:48 UTC
Labels: duplicate
