### ISSUE TITLE
Unable to exit from animation

### ISSUE THREAD

**Issue by Eddy5646** [itsamewayu/OLFallenDoll#261] opened 2021-12-03 01:22 UTC
**Describe the bug**
The game fails to exit from the active animation. When pressing the 'esc' key, the game does nothing. When pressing the exit button in the HUD, the icon becomes grayed out, but nothing further happens.

**To Reproduce**
1. Enter an animation in the Harem mode.
2. Attempt to exit the animation using either of the 2 displayed methods
3. When these fail, alt+f4 to escape the game

**Expected behavior**
Animation ends and free roam mode reengages.

**Additional context**
Only tested twice before the game became unplayable due to an unrelated bug, so testing was not extensive. In the trials that I did, both attempts to exit were made after having engaged in the animation for some time, including going through the climax - I do not know if the phase of the animation or how long it's been active has any impact on the issue.

**Comment by TheSoulWizard** [comment] 2021-12-03 05:15
@itsamewayu Duplicate to #100

**Comment by jinjin525** [comment] 2021-12-06 06:06
Confirmed duplicate of #100

**Closed by jinjin525** 2021-12-06 06:06 UTC
Labels: duplicate
