### ISSUE TITLE
What will change to ( cognitive filters ) when the sanity system is removed?

### ISSUE THREAD

**Issue by p0315167** [itsamewayu/OLFallenDoll#1162] opened 2024-01-25 21:05 UTC
What will change to cognitive filters when the sanity system is removed?
I used to get it through passes and daily login rewards, but I haven't used them and accumulated 62. Will these disappear when the sanity system is deleted? Will we be compensated?

当理智系统删除后，认知滤网会怎么处理? 
以前透过通行证、每日登录奖励领取，一直没有使用，累积了62个。
当理智系统删除后，这些会消失吗? 我们会有补偿吗?

**Additional pictures**
![20240126045312_1](https://github.com/itsamewayu/OLFallenDoll/assets/127018744/027ef01e-e5a0-415d-9ae2-c4bc26e2c5a7)
![20240126045300_1](https://github.com/itsamewayu/OLFallenDoll/assets/127018744/54d4a7cd-97f6-41be-be93-58c8e3a7e151)

**Comment by Awfulwaffle1** [comment] 2024-01-28 16:39
@p0315167 This is something we're still waiting on Helius to announce once the sanity system is removed. Not a bug so closing for now.

**Closed** 2024-01-28 16:41 UTC
Labels: Not A Bug
