### ISSUE TITLE
LoD of Textures of my girl between experiment/scene and walking around differ

### ISSUE THREAD

**Issue by Justify87** [itsamewayu/OLFallenDoll#240] opened 2021-12-02 15:23 UTC
When walking around, textures of my girl seem to be ok now. But when launching an experiment, they get a lot worse.
Other players are alway havin low res textures for me

**Comment by jinjin525** [comment] 2021-12-07 02:09
Duplicate of #183

**Closed by jinjin525** 2021-12-07 02:09 UTC
