### ISSUE TITLE
[Title][Menu] Multiple buttons stacking ontop of one another.

### ISSUE THREAD

**Issue by Mixifizz** [itsamewayu/OLFallenDoll#233] opened 2021-12-02 13:40 UTC
Bug: Multiple menu options after hitting quit to title from harem mode.

Recreation: Not a 100% bugg. Hitting quit to title over and over might pop it though.
![20211202073414_1](https://user-images.githubusercontent.com/95285648/144433124-9ce27181-f2c0-43dd-9227-b3743a3d7688.jpg)

**Comment by jinjin525** [comment] 2021-12-07 01:51
Duplicate of #176

**Closed by jinjin525** 2021-12-07 01:51 UTC
Labels: duplicate
