### ISSUE TITLE
[Harem] [UI] Daily tasks do not accumulate

### ISSUE THREAD

**Issue by Yoshiga-Jinya** [itsamewayu/OLFallenDoll#244] opened 2021-12-02 16:24 UTC
**Describe the bug**
The Daily task of "Make male ejaculate 10 times by conducting experiments with" Interspecies "tag." Is not counted.
It does not count in the male race of the Interspecies tag or in the Experiment with Dream man.

**Desktop (please complete the following information):**
- OS: [windows 10 home]
- RAM: [32GB]
- video card: [Geforce RTX 2060 Super]
- CPU: [Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz 4.00 GHz]

**Comment by jinjin525** [comment] 2021-12-03 05:22
Duplicate of #164

**Closed by jinjin525** 2021-12-03 05:22 UTC
