### ISSUE TITLE
[Harem] [Changeroom] [UI] Mouse cursor invisible on Changeroom

### ISSUE THREAD

**Issue by RueGorE** [itsamewayu/OLFallenDoll#119] opened 2021-11-30 06:53 UTC
**Describe the bug**
The mouse cursor disappears when starting Harem mode then going to the Changeroom from the Escape screen.

**To Reproduce**
0. I'm in Windowed mode
1. Go to Harem mode
2. [At this time] When stuck in elevator, press the Escape key and click on Changeroom option
3. Mouse cursor becomes invisible, although it can still interact with clickable elements if you try hard enough

**Expected behavior**
I expect the mouse cursor to never disappear.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro, 20H2

**Comment by jinjin525** [comment] 2021-12-06 07:03
Duplicate of #90

**Closed by jinjin525** 2021-12-06 07:03 UTC
Labels: duplicate
