### ISSUE TITLE
[UI] issue with arguments after accepting mail bonuses

### ISSUE THREAD

**Issue by fduser2** [itsamewayu/OLFallenDoll#210] opened 2021-12-02 01:14 UTC
![image](https://user-images.githubusercontent.com/95328775/144339726-002397f4-55f7-49dd-b21e-8b75c853f8e1.png)

Accepting the mail bonuses causes the arguments to go up (there's only actually 1 instead of 151)

**Comment by jinjin525** [comment] 2021-12-07 11:31
Duplicate of #266

**Closed by jinjin525** 2021-12-07 11:31 UTC
