### ISSUE TITLE
Currency disappeared after receiving boost pack

### ISSUE THREAD

**Issue by AlexanderHYu** [itsamewayu/OLFallenDoll#174] opened 2021-11-30 23:49 UTC
I received 100 currency (the one with light bulb) from the boost pack and only spent 20 on blue prints. I should still have 80 currency, but when I got stuck in the elevator once and rebooted the game, all my currency were gone. I have no idea what went wrong during the process, but this is obviously a serious issue.

**Comment by jinjin525** [comment] 2021-12-06 11:17
Duplicate of #102

**Closed by jinjin525** 2021-12-06 11:17 UTC
