### ISSUE TITLE
无法连接到Patreon

### ISSUE THREAD

**Issue by BugKLeo** [itsamewayu/OLFallenDoll#607] opened 2023-03-05 08:48 UTC
游戏点击Link Patreon无法链接到Patreon，跳转到官网后显示Cannot Update Player Data

![image](https://user-images.githubusercontent.com/127014378/222950881-2a41d098-a75b-4f3f-b2f3-5b63625a7f49.png)

**Comment by poykun** [comment] 2023-03-05 08:54
dupe of #596 
Current resolution is to give it an 1-2 hours for the data to sync prior to it updating properly.

**Comment by BugKLeo** [comment] 2023-03-05 11:02
已经超过2小时了，依旧无法链接Patreon，如果一直同步不了就只能一直等着吗，有没有其他解决方案？

**Comment by poykun** [comment] 2023-03-05 13:39
The team made an announcement in discord that the devs are working on the fix for the issue.

**Comment by Awfulwaffle1** [comment] 2023-06-11 08:02
No further tickets with this issue as of 0.7.3. Closing.

**Closed by Awfulwaffle1** 2023-06-11 08:02 UTC
Labels: Resolved
