### ISSUE TITLE
[EAC] Easy Anti Cheat not installed

### ISSUE THREAD

**Issue by Tunets92** [itsamewayu/OLFallenDoll#356] opened 2021-12-07 20:54 UTC
When opening the launcher it states that Easy Anti Cheat isn't installed. I've tried following the guides posted but trying to open EasyAntiCheat_EOS_Setup doesn't do anything or prompt a setup page.

**To Reproduce**
Can't reproduce the problem since I can't open it from the launcher. 

**Expected behavior**
Expected the game to launch.

**Screenshots**
![image](https://user-images.githubusercontent.com/95574697/145102501-f978fb8a-5acc-421a-86f7-7b00baa67923.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Game Version: 0.42
 Complete the following Computer Hardware Configurations if necessary:
 - Processor(CPU): R5 2600x
 - Graphics Card: RTX 3070Ti
 - Memory: 32 GB

**Additional context**
I've tried reinstalling the game multiple times and verifying the files. I've also checked my firewalls and security and it doesn't seem to have blocked it. I'm aware multiple people have posted this but I've yet to see a reply from the devs other than the post they put up in the FAQ.

**Comment by jinjin525** [comment] 2021-12-08 01:13
Duplicate of #193

**Closed by jinjin525** 2021-12-08 01:13 UTC
