### ISSUE TITLE
[Error] Signed out in Harem mode, can't use user ID.

### ISSUE THREAD

**Issue by Valamore** [itsamewayu/OLFallenDoll#149] opened 2021-11-30 15:25 UTC
The game crashed and when I relaunched it and entered harem mode again it asked for me to input my user ID like I was making a new account and now I can't enter because it won't accept my user ID saying it already exists.

**Comment by GroverChouT** [comment] 2021-12-01 10:42
#154

**Comment by jinjin525** [comment] 2021-12-06 08:27
confirmed Duplicate of #154

**Closed by jinjin525** 2021-12-06 08:27 UTC
