### ISSUE TITLE
anya's body disappeared

### ISSUE THREAD

**Issue by backtoChaos** [itsamewayu/OLFallenDoll#348] opened 2021-12-06 19:12 UTC
just encountered this during haram mode human only, after finishing a pose.
![image](https://user-images.githubusercontent.com/9326605/144907557-576d2a3a-afb6-40a6-928d-2fe66e833ca4.png)

**Comment by jinjin525** [comment] 2021-12-07 08:50
Duplicate of #337

**Closed by jinjin525** 2021-12-07 08:50 UTC

**Comment by reteriax** [comment] 2021-12-12 14:10
same as erika
![20211212212101_1](https://user-images.githubusercontent.com/95478401/145715857-2cf0dc88-7da1-46c2-95f7-8d3a4d0f0820.jpg)
