### ISSUE TITLE
[Camera][Harem] Cunninligus Piledriver

### ISSUE THREAD

**Issue by AvalonDelta** [itsamewayu/OLFallenDoll#243] opened 2021-12-02 15:49 UTC
**Describe the bug**
Camera does not properly position in the Cunninligus Piledriver Scene involving Alet/Anya

**To Reproduce**
1. Setup Cunninligus Piledriver (Alet/Anya) on any wall in the Space station area.
2. Camera zooms into a completely unrelated area, requiring you to freecam back to Alet and Anya

**Expected behavior**
Camera Positions itself correctly on Alet and Anya in the position.

**Screenshots**
Cannot capture camera behavior with screenshot

**Desktop (please complete the following information):**
 - OS: Windows 10]
 - Browser NA
 - Version [e.g. 0.41]

**Smartphone (please complete the following information):**
 - Device: NA
 - OS: NA
 - Browser NA
 - Version NA

**Additional context**
Replicated in multiple wall areas of Laboratory (including the glass wall), Workshop, Bridge. The camera will position in different rooms or even outside the map.

**Comment by fduser2** [comment] 2021-12-04 05:19
#168 #229 both have the same issue, linking them

**Comment by jinjin525** [comment] 2021-12-06 10:59
Confirmed duplicate of #168

**Closed by jinjin525** 2021-12-06 10:59 UTC
