### ISSUE TITLE
無法贈送角色禮物 Unable to give character gifts

### ISSUE THREAD

**Issue by amosteashop** [itsamewayu/OLFallenDoll#1107] opened 2024-01-04 04:34 UTC
**Describe the bug**

**To Reproduce**
1. Go to 'character'
2. Click on 'gift'
3. select  a gift
4. See error 'The gift slot disappears directly'

**Screenshots**
![vv](https://github.com/itsamewayu/OLFallenDoll/assets/155605413/e43cb3bf-aa51-4b57-a53f-314c8cc2e3a5)

**Desktop (please complete the following information):**
 - OS: [e.g. Win10/Ubuntu 20.04]
 - Game Version [e.g. 0.42]
 Complete the following Computer Hardware Configurations if necessary:
 - Processor(CPU): [Intel(R) Core(TM) i9-10900KF CPU @ 3.70GHz   3.70 GHz]
 - Graphics Card:[e.g. RTX 2070s]
 - Memory:[e.g. 16GB]

**Additional context**
fix it omg

**Comment by Awfulwaffle1** [comment] 2024-01-05 02:23
This is known and simply a feature that has not been implemented yet. Closing as not a bug.

**Closed by Awfulwaffle1** 2024-01-05 02:23 UTC
Labels: Not A Bug
