### ISSUE TITLE
Cursor will not reach full screen 

### ISSUE THREAD

**Issue by Captain-YeastyJ** [itsamewayu/OLFallenDoll#447] opened 2021-12-31 19:29 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Win10/Ubuntu 20.04]
 - Game Version [e.g. 0.42]
 Complete the following Computer Hardware Configurations if necessary:
 - Processor(CPU): [e.g. i7-9700K]
 - Graphics Card:[e.g. RTX 2070s]
 - Memory:[e.g. 16GB]

*If your game crashed, remember to upload the dmp file with your issue.

It's located in C:\Users\ (USER ID) \AppData\Local\Paralogue

**Additional context**

**Comment by Captain-YeastyJ** [comment] 2021-12-31 19:30
I cannot get my cursor to go to the right side of the screen, it stops about 4/5ths the way.

**Comment by TheSoulWizard** [comment] 2022-01-01 18:08
Duplicate of #74

**Closed** 2022-01-02 01:13 UTC
Labels: duplicate
