### ISSUE TITLE
[Harem] [UI] Sorting is not accurate

### ISSUE THREAD

**Issue by Kasaiji** [itsamewayu/OLFallenDoll#280] opened 2021-12-03 14:47 UTC
**Describe the bug**
Even if I select the Sort tab for each character in Experiments, Experiments of other characters are mixed.

**Screenshots**
![144454823-b5a66882-af66-486d-bf1b-2e4954a89c0c](https://user-images.githubusercontent.com/68011636/144621946-796012c7-d294-49bf-bf98-55c2a92e3487.jpg)

**Desktop (please complete the following information):**
- OS: [windows 10 home]
- RAM: [32GB]
- video card: [Geforce RTX 2060 Super]
- CPU: [Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz 4.00 GHz]

**Comment by jinjin525** [comment] 2021-12-07 04:42
Duplicate of #113

**Closed by jinjin525** 2021-12-07 04:42 UTC
