### ISSUE TITLE
[Camera] Camera starting in wrong spot/room

### ISSUE THREAD

**Issue by itsamewayu** [itsamewayu/OLFallenDoll#12] opened 2021-11-27 11:21 UTC
From TMoane

Alet laboratory scenes that put you in the wrong room or don't put the camera in the right spot 
![unknown](https://user-images.githubusercontent.com/11155504/143679068-f9186b2a-cf6f-4ec5-92ec-12587db8c905.png)
![unknown](https://user-images.githubusercontent.com/11155504/143679070-cbb1e5f6-9d7c-47bc-b104-a85c14a6eaeb.png)
![unknown](https://user-images.githubusercontent.com/11155504/143679072-05f71e58-346b-4f19-ada8-c0525bc7de68.png)
![unknown](https://user-images.githubusercontent.com/11155504/143679074-50c7c019-222d-42b7-8d96-482380de78ab.png)

Anya laboratory scenes that put you in the wrong room or don't put the camera in the right spot
![unknown](https://user-images.githubusercontent.com/11155504/143679083-3c46e784-5b66-466f-947b-8a3475067f48.png)

Alet workshop scenes that put you in the wrong room or don't put the camera in the right spot
![unknown](https://user-images.githubusercontent.com/11155504/143679090-698a7522-fe6f-42f6-bdb7-45c4701ed3f3.png)
![unknown](https://user-images.githubusercontent.com/11155504/143679092-aa6c6288-e295-4490-8a74-88bbb39a8f6f.png)
![unknown](https://user-images.githubusercontent.com/11155504/143679093-fdd2d88a-0921-4337-9699-7f739015e3e4.png)
![unknown](https://user-images.githubusercontent.com/11155504/143679098-cd4db7b6-26e3-4249-8082-2e80ef7e40b1.png)
![unknown](https://user-images.githubusercontent.com/11155504/143679102-ef3d2f87-c3f2-408f-931c-6836ba01019b.png)

Anya workshop scenes that put you in the wrong room or don't put the camera in the right spot
![unknown](https://user-images.githubusercontent.com/11155504/143679105-6c03997f-2ced-43fb-935d-90671919117e.png)
![unknown](https://user-images.githubusercontent.com/11155504/143679106-ce1ca1a8-7df3-4af0-b622-6e214bee9832.png)

**From 别扒拉我~**
阿蕾特 跪姿口BUG
![unknown](https://user-images.githubusercontent.com/11155504/143678829-f04321a7-99bd-4ce4-b8f0-85c849df118f.png)
_MIYA NOTE: User did not specify what was the issue here exactly, likely wrong camera starting position_

**Comment by jinjin525** [comment] 2021-12-05 04:03
Duplicate of #5

**Closed by jinjin525** 2021-12-05 04:03 UTC
Labels: duplicate
