### ISSUE TITLE
how to give a gift to a girl

### ISSUE THREAD

**Issue by ijs77** [itsamewayu/OLFallenDoll#1069] opened 2023-12-28 08:12 UTC
**Describe the bug**
how to give a gift to a girl, and please give the hairy option

**Comment by Awfulwaffle1** [comment] 2023-12-29 16:21
@ijs77 Closing this as it's a known thing, but not a bug. The affinity system has not been fully implemented yet.
As for the hairy option it's been suggested and may be slated for a release later. Closing.

**Closed by Awfulwaffle1** 2023-12-29 16:21 UTC
Labels: Not A Bug
