### ISSUE TITLE
Game crash -> cant get back into Harem Mode

### ISSUE THREAD

**Issue by alfi301** [itsamewayu/OLFallenDoll#135] opened 2021-11-30 08:53 UTC
I connected to Harem Mode and was able to perform one animation ([clipping bug](https://github.com/itsamewayu/OLFallenDoll/issues/134)) after that I went to the changing room to potentially fix the clipping mentioned in the other ticket. My game crashed with an error message. I restarted the game but seemingly I can not log in to Harem mode anymore. I click on it, the loading symbol displays, the loading screen / map shows up and I get sent back to main menu. No messages or anything displays.
If helpful my steam account name is alfneufert and the character ID was DARKLORD301.

**Comment by alfi301** [comment] 2021-11-30 09:02
Probably attach this to [this bug](https://github.com/itsamewayu/OLFallenDoll/issues/86)

**Comment by jinjin525** [comment] 2021-12-06 08:02
Confirmed duplicate of #86

**Closed by jinjin525** 2021-12-06 08:02 UTC
