### ISSUE TITLE
[Model] Dr. Anya Pilot Suit

### ISSUE THREAD

**Issue by LeoMachiavelli** [itsamewayu/OLFallenDoll#425] opened 2021-12-27 16:59 UTC
When using the Pilot Suit for Dr. Anya and selecting Upper Apparel as Half dressed. You can produce a noticeable gap between her head and body, you can see right through her neck essentially. It is visible on all places that model can be used.

**Comment by johnathandarkly** [comment] 2021-12-28 06:16
duplicate of #70

**Comment by jinjin525** [comment] 2021-12-29 06:02
Confirmed duplicate of #70

**Closed by jinjin525** 2021-12-29 06:02 UTC
Labels: 0.4.5
