### ISSUE TITLE
Experiments under wrong category (i.e. Dr.Anya/Alet/Erika) on EXPERIMENTS list UI

### ISSUE THREAD

**Issue by clifftor** [itsamewayu/OLFallenDoll#383] opened 2021-12-12 16:44 UTC
**Describe the bug**
Multiple cards listed in the wrong category, e.g.
Erika's `Kneeling Missionary`, Alet's `Doggystyle on Crane` and `On Back Footjob` are under Dr.Anya's tab.

**To Reproduce**
Go to the Harem mode, select EXPERIMENTS in the main UI.
Select `Dr.Anya`, `Alet` or `Erika` tab. Some cards are under wrong category.

**Full list of cards under incorrect category**
* Tab `Dr.Anya`
  * Erika's `Kneeling Missionary`
  * Alet's `Doggystyle on Crane`
  * Alet's `On Back Footjob`
* Tab `Alet`
  * Erika's `Reverse Footjob`
  * Erika's `Squatting Cowgirl`
  * Erika's `Betty Rocker`
  * Erika's `Thrust Behind`
  * Erika's `Hands Bound Missionary`
  * Erika's `Hugging Cowgirl`
  * Anya's `Feet Held Footjob`
  * Anya's `Anal Missionary`
  * Anya's `Threesome Reverse Cowgirl Double Penetration`
  * Anya's `Prone Bone`
  * Anya's `Threesome Kneeling Spitroast with Standing Blowjob`
* Tab `Erika`
  * Alet's `Reclined Entry`
  * Alet's `Fondling Handjob`
  * Alet's `Doggystyle Massage`
  * Alet's `Leg Raised Missionary`
  * Alet's `Leg-up Kneeling Blowjob`
  * Anya's `Handcuffed Crouch Anal`
  * Anya's `Bent Over Rear Entry On Table`

**Screenshots**
![wrong_category](https://user-images.githubusercontent.com/20754595/145720637-aaef1185-5eb1-407c-b7d1-d0fb4e53d43c.png)
![wrong_category_2](https://user-images.githubusercontent.com/20754595/145720640-ef6a2324-d228-42ff-90e2-8b9839cbdc9b.png)

**Comment by Panthear** [comment] 2021-12-15 18:44
Duplicate of #113

**Comment by jinjin525** [comment] 2021-12-17 04:37
Duplicated but will keep this open for a while since it listed all detailed information

**Comment by clifftor** [comment] 2021-12-17 07:41
You can move the list into #113

**Comment by jinjin525** [comment] 2021-12-19 07:11
Copied the list into #113.

**Closed by jinjin525** 2021-12-19 07:11 UTC
