### ISSUE TITLE
[Harem][Menu][UI] Insufficient Argument/ unable to purchase new blueprints

### ISSUE THREAD

**Issue by TextAfterDark** [itsamewayu/OLFallenDoll#169] opened 2021-11-30 21:31 UTC
Trying to purchase additional packs via blueprint with arguments seem to not work.
Unsure if this a graphical error on the number of arguments i have or something else.  
Please Note: The argument that i have seem to go up and down.
I started with 48 with the first time login but with the server crash and a game crash it went down to zero, then it when back to 150 when i accepted the in-game mail.

**Screenshots**
![image](https://user-images.githubusercontent.com/95316882/144130085-bc87d2fc-9d00-47da-a622-b22add785bae.png)

**Comment by jinjin525** [comment] 2021-12-06 11:10
Duplicate of #102

**Closed by jinjin525** 2021-12-06 11:10 UTC
