### ISSUE TITLE
[Quest] Quest not refreshing

### ISSUE THREAD

**Issue by lyc2371606223** [itsamewayu/OLFallenDoll#335] opened 2021-12-05 17:51 UTC
I finished all three quests a few days ago. One quest was refreshed the following day but the others doens't.

**Comment by jinjin525** [comment] 2021-12-07 08:16
One quest freshes every day.

**Comment by lyc2371606223** [comment] 2021-12-07 09:06
@jinjin525 Well perhaps I didn't make it clear. I cannot remember the exact date but let's assume I finished 3 quests on Dec 1st. Then one quest refreshed on 2nd. But from 3rd on the quests no longer refreshes.

**Comment by lyc2371606223** [comment] 2021-12-07 09:09
I think the problem happened along with being kicked out from loading page, which was mentioned in today’s progress report.

**Comment by jinjin525** [comment] 2021-12-08 04:42
Duplicate of #277 in this case

**Closed by jinjin525** 2021-12-08 04:43 UTC
