### ISSUE TITLE
Bug of getting stuck in chairs on the Nightclub map

### ISSUE THREAD

**Issue by SuNNLov** [itsamewayu/OLFallenDoll#937] opened 2023-10-06 21:01 UTC
**Describe the bug**
When you are on the Nightclub map with a character with belly bulge active, if you sit on a chair or in any masturbation area and start the act, and during the act press the button to release the fluids, the animation breaks and you are trapped in the chair, unable to get out of it.
In the end, you need to restart the game to solve it.

**Desktop (fill in the following information):**
        - OS: Win 11 Pro
        - Game version: 0.7.5d

**Comment by Awfulwaffle1** [comment] 2023-11-23 06:09
Looks to be resolved as of 0.7.7d as I could not reproduce the issue. Closing, but feel free to re-open if the issue persists on your end @SuNNLov

**Closed by Awfulwaffle1** 2023-11-23 06:09 UTC
Labels: System, Resolved, 0.7.5d
