### ISSUE TITLE
[Harem] [model] Clipping issue in dressing room 

### ISSUE THREAD

**Issue by Joshua40004** [itsamewayu/OLFallenDoll#126] opened 2021-11-30 07:36 UTC
![clipping](https://user-images.githubusercontent.com/66255486/144005182-6174d33d-f7cf-455b-ac2f-277c90b1e352.png)

**Comment by jinjin525** [comment] 2021-12-06 07:34
Duplicate of #31

**Closed by jinjin525** 2021-12-06 07:34 UTC
