### ISSUE TITLE
[Controls] Special actions usually don't work

### ISSUE THREAD

**Issue by apugo** [itsamewayu/OLFallenDoll#181] opened 2021-12-01 02:10 UTC
The special actions (special 1, special 2, special 3) available with some experiments do not work. Pressing the corresponding key on the keyboard does nothing, and clicking on the body part does nothing. Sometimes the cursor changes to something that looks a little like a fist, but it still doesn't trigger the special interaction.

Some poses, like Apollo (Erika with Ghast) work fine with the keyboard. Others work sometimes when you click, like Erika with the Dreamer's "Betty Rocker." Others, like Erika with the byakhee's "choking missionary," do not work at all.

**Comment by jinjin525** [comment] 2021-12-06 12:41
Duplicate of #200

**Closed by jinjin525** 2021-12-06 12:41 UTC
Labels: duplicate
