### ISSUE TITLE
Daily objective bugged

### ISSUE THREAD

**Issue by DonCarlon** [itsamewayu/OLFallenDoll#468] opened 2022-01-04 20:55 UTC
**Describe the bug**
The Daily Objective is bugged, where there would usually be a challenge in the harem menu it says “taskId:0”. 

**To Reproduce**
1. It was a few days ago but I think it was caused by receiving 2 of the same task at once. If I remember right before it changed to “taskId” there was 2 of the same task. Then it changed to this.

**Expected behavior**
I now have 1 less task slot since it always shows “taskId”, also the game has been crashing more frequently since then

**Screenshots**
![issue](https://user-images.githubusercontent.com/97128829/148123177-e90a40f9-165c-46dc-bf23-3ff3d428ffe5.PNG)

**Desktop (please complete the following information):**
 - OS: [e.g. Win10

 - Game Version 0.4.5
 Complete the following Computer Hardware Configurations if necessary:
 - Graphics Card: RTX 2070s
 - Memory: 16GB

**Comment by TheSoulWizard** [comment] 2022-01-04 21:02
Duplicate of #446

**Closed** 2023-11-23 02:23 UTC
